package sqlQueries;

public class StringQueries {

	public static String INSERT_PERSON_QUERY = "INSERT INTO PERSON (ID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,EMAIL,DOB) VALUES (?,?,?,?,?,?,?)";
	
	public static String INSERT_DEVELOPER_QUERY = "INSERT INTO DEVELOPER (ID, PERSON, DEVELOPERKEY) VALUES (?,?,?)";
	
	public static String FIND_ALL_DEVELOPERS = 			
			"SELECT P.*, D.DEVELOPERKEY "
					+ "FROM DEVELOPER D,PERSON P "
					+ "WHERE D.PERSON = P.ID ";
	
	public static String FIND_DEVELOPER_BY_ID = 	
			"SELECT P.*, D.DEVELOPERKEY "
					+ "FROM DEVELOPER D,PERSON P "
					+ "WHERE D.PERSON = P.ID "
					+ "AND D.ID = ?";
	
	public static String FIND_DEVELOPER_BY_USERNAME = 	
			"SELECT P.*, D.DEVELOPERKEY "
					+ "FROM DEVELOPER D,PERSON P "
					+ "WHERE D.PERSON = P.ID "
					+ "AND P.USERNAME = ?";
	
	public static String FIND_DEVELOPER_BY_CREDENTIALS = 	
			"SELECT P.*, D.DEVELOPERKEY "
					+ "FROM DEVELOPER D,PERSON P "
					+ "WHERE D.PERSON = P.ID "
					+ "AND P.USERNAME = ? "
					+ "And P.PASSWORD = ?";
	
	public static String UPDATE_PERSON = "UPDATE PERSON SET FIRSTNAME = ?, LASTNAME = ?, USERNAME = ?, PASSWORD = ?, EMAIL = ?, DOB = ? "
			+ "WHERE ID = (SELECT PERSON FROM DEVELOPER WHERE DEVELOPER.ID = ?)";
	
	public static String UPDATE_DEVELOPER = "UPDATE DEVELOPER SET PERSON = ?, DEVELOPERKEY = ? WHERE DEVELOPER.ID = ?";
	
	public static String DELETE_DEVELOPER = "DELETE FROM DEVELOPER WHERE DEVELOPER.ID = ?";
	
	public static String DELETE_PERSON = "DELETE FROM PERSON WHERE ID = (SELECT PERSON FROM DEVELOPER WHERE DEVELOPER.ID = ?)" ;

	public static String CREATE_WEBSITE = "INSERT INTO WEBSITE (ID,NAME,DESCRIPTION,CREATED,UPDATED,VISITS,DEVELOPER) VALUES (?,?,?,?,?,?,?)";
	
	public static String ASSIGN_WEBISTE_ROLE = "INSERT INTO WEBSITEROLE (ROLE, WEBSITE, DEVELOPER) VALUES (?, ?, ?)";
	
	public static String FIND_ROLE_ID_BY_NAME = "SELECT ID FROM ROLE WHERE ROLEDESCRIPTION = ?";
	
	public static String FIND_ROLE_ID_BY_DEV_ID_AND_PAGE_ID = "SELECT ROLE FROM PAGEROLE WHERE DEVELOPER =? AND PAGE =?";
	
	public static String FIND_ROLES_FOR_PAGE = "SELECT * FROM PAGEROLE WHERE PAGE =?";
	
	public static String FIND_WEBSITE_ID_BY_WEBSITE_NAME = "SELECT ID FROM WEBSITE WHERE NAME = ?";
	
	public static String FIND_DEVELOPER_ID_BY_NAME = "SELECT ID FROM DEVELOPER WHERE PERSON = (SELECT ID FROM PERSON WHERE USERNAME = ?)";
	
	public static String FIND_ALL_WEBSITES = "SELECT * FROM WEBSITE";
	
	public static String FIND_WEBSITES_FOR_DEVELOPER = "SELECT * FROM WEBSITE WHERE DEVELOPER = (SELECT ID FROM DEVELOPER WHERE ID = ?)";
	
	public static String FIND_WEBSITE_BY_ID = "SELECT * FROM WEBSITE WHERE ID = ?";
	
	public static String UPDATE_WEBSITE = "UPDATE WEBSITE SET NAME = ?,DESCRIPTION =? ,CREATED =?,UPDATED =?,VISITS =? ,DEVELOPER =? WHERE ID = ?";
	
	public static String DELETE_WEBSITE = "DELETE FROM WEBSITE WHERE ID = ?";
	
	public static String DELETE_WEBSITE_ROLE_BY_WEBSITE_ID = "DELETE FROM WEBSITEROLE WHERE WEBSITE = ?";
	
	public static String DELETE_WEBSITE_ROLE = "DELETE FROM WEBSITEROLE WHERE DEVELOPER =? AND WEBSITE = ? AND ROLE =?";
	
	public static String FIND_PERSON_ID_BY_NAME = "SELECT ID FROM PERSON WHERE USERNAME = ?";
	
	public static String CREATE_PAGE = "INSERT INTO PAGE (ID,TITLE,DESCRIPTION,CREATED,UPDATED,VIEWS,WEBSITE) VALUES (?,?,?,?,?,?,?)";
	
	public static String FIND_PAGE_ID_BY_PAGE_NAME = "SELECT ID FROM PAGE WHERE TITLE = ?";
	
	public static String FIND_PAGE_ID_BY_PAGE_NAME_AND_WEBSITE_ID = FIND_PAGE_ID_BY_PAGE_NAME + " AND WEBSITE = ?";
	
	public static String ASSIGN_PAGE_ROLE = "INSERT INTO PAGEROLE (ROLE, PAGE, DEVELOPER) VALUES (?, ?, ?)";
	
	public static String FIND_ALL_PAGES = "SELECT * FROM PAGE";
	
	public static String FIND_PAGE_BY_ID = "SELECT * FROM PAGE WHERE ID = ?";
	
	public static String FIND_PAGE_BY_WEBSITE_ID = "SELECT * FROM PAGE WHERE WEBSITE IN (SELECT ID FROM WEBSITE WHERE ID = ?)";
	
	public static String FIND_LAST_UPDATED_PAGE_ID_BY_WEBSITE_ID = " SELECT ID FROM PAGE WHERE WEBSITE = ? ORDER BY UPDATED DESC LIMIT 1 ";
	
	public static String UPDATE_PAGE = "UPDATE PAGE SET TITLE = ?,DESCRIPTION =? ,CREATED =?,UPDATED =?,VIEWS =? ,WEBSITE =? WHERE ID = ?";
	
	public static String DELETE_PAGE = "DELETE FROM PAGE WHERE ID = ?";
	
	public static String DELETE_PAGE_ROLE = "DELETE FROM PAGEROLE WHERE DEVELOPER =? AND PAGE = ? AND ROLE =?";
	
	public static String DELETE_PAGE_ROLE_BY_PAGE_ID = "DELETE FROM PAGEROLE WHERE PAGE = ?";
	
	public static String CREATE_WIDGET = "INSERT INTO WIDGET (ID,NAME,WIDTH,HEIGHT,CSSSTYLE,CSSCLASS,TEXT,WIDGETORDER,URL,SHARABLE,EXPANDABLE,SRC,SIZE,HTML,TYPE,PAGE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	
	public static String FIND_ALL_WIDGETS = "SELECT * FROM WIDGET";
	
	public static String FIND_WIDGET_BY_ID = "SELECT * FROM WIDGET WHERE ID = ?";
	
	public static String FIND_WIDGET_ID_BY_WIDGETNAME = "SELECT ID, PAGE FROM WIDGET WHERE NAME = ?";
	
	public static String FIND_WIDGET_BY_PAGE_ID = "SELECT * FROM WIDGET WHERE PAGE = (SELECT ID FROM PAGE WHERE ID = ?) ";
	
	public static String UPDATE_WIDGET = 
			"UPDATE WIDGET SET NAME =? ,WIDTH =? ,HEIGHT =? "
			+ ",CSSSTYLE =? ,CSSCLASS =? ,TEXT =? ,WIDGETORDER =? ,URL =? ,SHARABLE =? ,EXPANDABLE =? ,SRC =? ,"
			+ "SIZE =? ,HTML =? ,TYPE =? , PAGE =? WHERE ID = ? ";
	
	public static String FIND_LAST_UPDATED_WIDGET_ID_BY_PAGE_ID = " SELECT ID FROM WIDGET WHERE PAGE = ? ORDER BY WIDGETORDER DESC LIMIT 1 ";
	
	public static String DELETE_WIDGET = "DELETE FROM WIDGET WHERE ID = ?";
	
	public static String FIND_PRIVILEGE_ID_BY_ROLE = "SELECT PRIVILEGE FROM ROLEPRIVILEGE WHERE ROLE = ?";
	
	public static String FIND_PRIVILEGE_ID_BY_NAME = "SELECT ID FROM PRIVILEGE WHERE PRIVILEGEDESCRIPTION = ?";
	
	public static String ASSIGN_WEBISTE_PRIVILEGE = "INSERT INTO WEBSITEPRIVILEGE (PRIVILEGE, WEBSITE, DEVELOPER) VALUES (?, ?, ?)";
	
	public static String ASSIGN_PAGE_PRIVILEGE = "INSERT INTO PAGEPRIVILEGE (PRIVILEGE, PAGE, DEVELOPER) VALUES (?, ?, ?)";
	
	public static String DELETE_WEBSITE_PRIVILEGE = "DELETE FROM WEBSITEPRIVILEGE WHERE DEVELOPER =? AND WEBSITE = ? AND PRIVILEGE =?";
	
	public static String DELETE_WEBSITE_PRIVILEGE_BY_WEBSITE_ID = "DELETE FROM WEBSITEPRIVILEGE WHERE WEBSITE = ?";
	
	public static String DELETE_PAGE_PRIVILEGE = "DELETE FROM PAGEPRIVILEGE WHERE DEVELOPER =? AND PAGE = ? AND PRIVILEGE =?";
	
	public static String DELETE_PAGE_PRIVILEGE_BY_PAGE_ID = "DELETE FROM PAGEPRIVILEGE WHERE PAGE = ?";
}

